on:

  pull_request:
    branches: [development]
  push:
    branches: [development]

permissions:
  contents: write

jobs:

  build:
    strategy:
      matrix:
        go-version: [ 1.21.4 ]
        os: [ ubuntu-latest ]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
      - name: Display Go Version
        run: go version
      - name: Install Dependencies
        run: go get .
      - name: Build Linux ARM64
        run: GOOS=linux GOOARCH=arm64 go build -v -o s3packer-linux-arm64 ./...
      - name: Build Linux AMD64
        run: GOOS=linux GOOARCH=amd64 go build -v -o s3packer-linux-amd64 ./...
      - name: Build MacOS ARM64
        run: GOOS=darwin GOOARCH=arm64 go build -v -o s3packer-mac-arm64 ./...
      - name: Build MacOS AMD64
        run: GOOS=darwin GOOARCH=amd64 go build -v -o s3packer-mac-amd64 ./...
      - name: Locate Binaries
        run: ls -la