---
name: Go Tests

on:
  push:
    paths: [ '**.go' ]
    branches-ignore:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.5

      - name: Go Format
        run: gofmt -s -w . && git diff --exit-code

      - name: Get Dependencies
        run: go get ./...

      - name: Go Tests
        run: go test -v -count=1 -race -shuffle=on -coverprofile=coverage.txt ./...