---
name: Go Tests

on:
  pull_request:
    branches: [ master ]
    types: [ opened ]

  push:
    paths: [ '**.go' ]
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.0
          check-latest: true

      - name: Go Format
        run: gofmt -s -w . && git diff --exit-code

      - name: Get Dependencies
        run: go get ./...

#      - name: Go Tests
#        run: go test -v -count=1 -race -shuffle=on -coverprofile=coverage.txt ./...

      - name: Test ./internal/distlog
        run: go test -v -count=1 -race -shuffle=on ./internal/distlog

      - name: Test ./internal/conf
        run: go test -v -count=1 -race -shuffle=on ./internal/conf

#        objectify is causing data races, that needs to be fixed
#        run: go test -v -count=1 -race -shuffle=on ./internal/provider
      - name: Test ./internal/provider
        run: go test -v -count=1 -shuffle=on ./internal/provider

